# App
spring.application.name=urlshortener
server.port=8080

# PostgreSQL ? change username/password to yours
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Base URL (used to build short links)
app.base-url=http://localhost:8080

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# Connection pool ? reuses connections instead of creating new ones each time
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1

# Show your custom debug logs
logging.level.com.kushagra.urlshortener=DEBUG

# Optional but useful ? shows Redis commands being fired
logging.level.io.lettuce.core=DEBUG
```

# Cache TTL default (24 hours) ? how long items stay in cache
app.cache.ttl-hours=24